server:
  port: 80
  servlet:
    context-path: /
  address: localhost

spring:
  application:
    name: spring-boot-template
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&&allowPublicKeyRetrieval=true
    username: root
    password: Hx123456!
    druid:
      filters: stat,wall
      maxActive: 10
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  profiles:
    active: @env@

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    aggressive-lazy-loading: false
  global-config:
    db-config:
      logic-delete-value: 1
